version: '3.8'

services:
  app:
    build: .
    ports:
      - "8090:8090"
    volumes:
      - pb_data:/pb/pb_data
      - ./pb_migrations:/pb/pb_migrations
    restart: always

volumes:
  pb_data:
