FROM alpine:latest

# Install dependencies for PocketBase
RUN apk add --no-cache \
    unzip \
    ca-certificates \
    curl \
    sqlite

# PocketBase version
ENV PB_VERSION=0.36.4

# Download and install PocketBase
RUN curl -Ls https://github.com/pocketbase/pocketbase/releases/download/v${PB_VERSION}/pocketbase_${PB_VERSION}_linux_amd64.zip -o /tmp/pb.zip && \
    unzip /tmp/pb.zip -d /pb/ && \
    rm /tmp/pb.zip

WORKDIR /pb

EXPOSE 8090

# Start PocketBase
CMD ["./pocketbase", "serve", "--http=0.0.0.0:8090", "--dir=/pb/pb_data"]
