services:
  # PocketBase for local development
  pb:
    build:
      context: .
      dockerfile: Dockerfile-dev
    container_name: ponto-pb-dev
    ports:
      - "8090:8090"
    volumes:
      - pb_data:/pb/pb_data
      - ./pb_migrations:/pb/pb_migrations
      - ./pb_hooks:/pb/pb_hooks
    restart: unless-stopped

volumes:
  pb_data:
    name: ponto_pb_data
