services:
  # Production build (Frontend + PocketBase in a single container)
  production:
    build: .
    container_name: ponto-app-prod
    ports:
      - "8080:8080"
    volumes:
      - ./pb_data:/pb/pb_data
    environment:
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    restart: unless-stopped
